### PR TITLE
J skord#284

### PR DESCRIPTION
**Pull request by jskord**
got rid of excess links in nav bar.  added text to homepage that describes basic site functions.

### CODE REVIEW

**Comment by paulyk1983** [comment]
The changes look good but there a ton of merge conflicts scattered throughout the files, so I cannot merge it as is. You can see where the conflicts are in github's "Files changed" section.

**Comment by jskord** [comment]
Are you talking about the last commit "conflicts"? those are all conflicts
I fixed based on your last pull request, when you deleted and changed a
bunch of files.

**Comment by jskord** [comment]
If there were merge conflicts, the box wouldn't have been green and said
"able to merge"

**Comment by paulyk1983** [comment]
Well, at any rate, those files need to be corrected before your branch can be moved. I do not see the errors on my local branches or on the current github.

**Comment by paulyk1983** [comment]
Also, make sure pull down often. I just made some revisions and pushed directly to qa.

**Pull request closed without merging**
